const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');

async function main() {
  const env={...process.env,ATELIER_URL:'http://127.0.0.1:4335/',ATELIER_DESKTOP_TEST:'1'};
  delete env.ELECTRON_RUN_AS_NODE;
  const app=await electron.launch({executablePath:require('electron'),args:[path.resolve('desktop/main.cjs'),'--atelier-code'],env,timeout:30000});
  const evidence=path.resolve('.atelier/workspace-evidence'),errors=[];
  fs.mkdirSync(evidence,{recursive:true});
  try {
    const page=await app.firstWindow({timeout:20000});page.setDefaultTimeout(15000);
    page.on('pageerror',error => errors.push(error.message));
    await app.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].webContents.setBackgroundThrottling(false));
    await page.locator('#native-terminal').waitFor();
    await page.waitForFunction(() => provider().models.length > 0);
    await page.evaluate(() => {nativeTerminalLayout='free';nativeWorkspaceLayout().dashboardVisible=false;render();});
    const ids=await page.evaluate(async () => {
      await createNativeTerminal({runtime:'codex',model:'fixture-code',sandbox:'read-only',name:'Recette · Principal'});
      const first=activeNativeTerminal;
      await createNativeTerminal({runtime:'omp',model:'fixture-code',sandbox:'read-only',name:'Recette · Revue',placement:{anchorId:first,side:'right'}});
      const second=activeNativeTerminal;
      await createNativeTerminal({runtime:'codex',model:'fixture-code',sandbox:'read-only',name:'Recette · Tests',placement:{anchorId:second,side:'bottom'}});
      return [first,second,activeNativeTerminal];
    });
    await page.waitForFunction(() => [...nativeTerminals.values()].every(tab => Array.from({length:tab.terminal.buffer.active.length},(_,index) => tab.terminal.buffer.active.getLine(index)?.translateToString()).join('\n').includes('ATELIER_PTY_READY')));
    assert.equal(await page.locator('.native-terminal-pane').count(),3);
    const geometry=await page.locator('.native-terminal-pane').evaluateAll(panes => panes.map(pane => {const rect=pane.getBoundingClientRect();return {id:pane.dataset.terminalPane,x:rect.x,y:rect.y,width:rect.width,height:rect.height};}));
    assert.ok(geometry[0].height > geometry[1].height*1.5);
    assert.ok(geometry[1].x > geometry[0].x && geometry[2].y > geometry[1].y);
    const vertical=page.locator('.terminal-layout-separator[aria-orientation=vertical]').first();
    await vertical.focus();const prior=Number(await vertical.getAttribute('aria-valuenow'));
    await page.keyboard.press('ArrowRight');assert.ok(Number(await vertical.getAttribute('aria-valuenow')) > prior);
    const horizontal=page.locator('.terminal-layout-separator[aria-orientation=horizontal]').first();
    const bounds=await horizontal.boundingBox();
    await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);await page.mouse.down();
    await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2+35,{steps:5});await page.mouse.up();
    assert.ok(Number(await horizontal.getAttribute('aria-valuenow')) > 50);
    await page.getByRole('button',{name:'Dashboard',exact:true}).click();
    await page.locator('.dashboard-dock').waitFor();
    assert.equal(await page.locator('.dashboard-groups').evaluate(groups => groups.scrollTop),0,'The dashboard starts at its highest priority groups');
    await page.waitForFunction(() => state.nativeSessions.length >= 3);
    assert.equal(await page.locator('.dashboard-dock .dashboard-agent[data-agent-kind=child]').count(),3);
    const terminalUnknown=await page.evaluate(id => dashboardAgents().find(agent => agent.id === id).status,ids[0]);
    assert.equal(terminalUnknown,'unknown');
    await page.screenshot({path:path.join(evidence,'free-terminals-dashboard.png')});
    const source=page.locator(`[data-terminal-drag="${ids[2]}"]`), target=page.locator(`[data-terminal-pane="${ids[0]}"]`);
    await source.dragTo(target,{sourcePosition:{x:10,y:10},targetPosition:{x:60,y:10}});
    assert.equal(await page.locator('.native-terminal-pane').count(),3);
    const moved=await page.locator(`[data-terminal-pane="${ids[2]}"]`).boundingBox();
    const original=await page.locator(`[data-terminal-pane="${ids[0]}"]`).boundingBox();
    assert.ok(moved.x < original.x+5 && moved.y < original.y,'Dropping on the top edge stacks the pane above its target');
    const rootBefore=await page.evaluate(() => JSON.stringify(nativeWorkspaceLayout().root));
    await page.locator('[name=codeWorkspace]').selectOption('workspace-b');
    assert.equal(await page.locator('.native-terminal-pane').count(),0);
    await page.evaluate(async () => createNativeTerminal({projectId:'workspace-b',runtime:'codex',model:'fixture-code',sandbox:'read-only',name:'Recette · Projet B'}));
    assert.equal(await page.locator('.native-terminal-pane').count(),1);
    const foreignId=await page.evaluate(() => activeNativeTerminal);
    await page.locator('[name=codeWorkspace]').selectOption('atelier');
    assert.equal(await page.locator('.native-terminal-pane').count(),3);
    assert.equal(await page.evaluate(() => JSON.stringify(nativeWorkspaceLayout().root)),rootBefore);
    assert.equal(await page.locator('.dashboard-dock').count(),1);
    await page.locator('[data-action=terminal-layout][data-layout=grid]').click();
    assert.equal(await page.locator('.native-terminal-pane').count(),3);
    await page.locator('[data-action=terminal-layout][data-layout=tabs]').click();
    assert.equal(await page.locator('.native-terminal-pane').count(),1);
    await page.locator('[data-action=terminal-layout][data-layout=free]').click();
    assert.equal(await page.locator('.native-terminal-pane').count(),3);
    await page.locator(`[data-terminal-pane="${ids[0]}"] [data-action=zoom-native-terminal]`).click();
    assert.equal(await page.locator('.native-terminal-pane').count(),1);
    await page.locator('[data-action=zoom-native-terminal]').click();
    assert.equal(await page.locator('.native-terminal-pane').count(),3);
    await page.evaluate(id => window.atelierDesktop.writeTerminal(id,'workspace-terminal-test\r'),foreignId);
    await page.waitForFunction(id => nativeTerminals.get(id).exited,foreignId);
    const echoed=await page.evaluate(id => {const buffer=nativeTerminals.get(id).terminal.buffer.active;return Array.from({length:buffer.length},(_,index) => buffer.getLine(index)?.translateToString()).join('\n').includes('ECHO:workspace-terminal-test');},foreignId);
    assert.equal(echoed,true,'Hidden workspaces retain a working PTY');
    await page.locator(`[data-terminal-pane="${ids[2]}"] [data-action=close-native-terminal]`).click();
    assert.equal(await page.locator('.native-terminal-pane').count(),2);
    assert.equal(await page.evaluate(() => TerminalLayout.paneIds(nativeWorkspaceLayout().root).length),2);
    await app.evaluate(({BrowserWindow}) => {const window=BrowserWindow.getAllWindows()[0];window.setMinimumSize(300,300);window.setContentSize(390,850);});
    await page.waitForTimeout(200);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth+1),false);
    await page.screenshot({path:path.join(evidence,'free-terminals-mobile.png'),fullPage:true});
    await page.evaluate(async () => {for (const id of [...nativeTerminals.keys()]) await actions['close-native-terminal']({dataset:{id}});});
    assert.equal(await page.locator('.xterm').count(),0);
    assert.deepEqual(errors,[]);
    fs.writeFileSync(path.join(evidence,'desktop-result.json'),JSON.stringify({passed:true,fixture:true,realPty:true,geometry,resizeBothAxes:true,dragToEdge:true,workspaceIsolation:true,echoed,zoomAndCollapse:true,dashboard:true,errors},null,2));
    console.log('Workspace desktop recipe passed: real PTYs, free splits, both resize axes, drag, workspace isolation, hidden PTY echo, dashboard, mobile, clean closure.');
  } finally {await app.close();}
}
main().catch(error => {console.error(error);process.exitCode=1;});
