const {contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('atelierDesktop',Object.freeze({
  updateState:() => ipcRenderer.invoke('updates:state'),
  updatePreferences:preferences => ipcRenderer.invoke('updates:preferences',preferences),
  checkUpdates:() => ipcRenderer.invoke('updates:check'),
  downloadUpdate:() => ipcRenderer.invoke('updates:download'),
  installUpdate:() => ipcRenderer.invoke('updates:install'),
  onUpdateState:callback => { const listener=(_event,status) => callback(status); ipcRenderer.on('updates:state',listener); return () => ipcRenderer.removeListener('updates:state',listener); },
  setZoom:percent => ipcRenderer.invoke('display:zoom',percent),
  onZoomShortcut:callback => { const listener=(_event,direction) => callback(direction); ipcRenderer.on('display:zoom-shortcut',listener); return () => ipcRenderer.removeListener('display:zoom-shortcut',listener); },
  createBrowser:id => ipcRenderer.invoke('browser:create',id),
  closeBrowser:id => ipcRenderer.invoke('browser:close',id),
  showBrowser:id => ipcRenderer.send('browser:show',id),
  browserBounds:bounds => ipcRenderer.send('browser:bounds',bounds),
  dragFile:resource => ipcRenderer.invoke('resource:drag',resource),
  navigateBrowser:(id,action) => ipcRenderer.invoke('browser:navigate',id,action),
  zoomBrowser:(id,percent) => ipcRenderer.invoke('browser:zoom',id,percent),
  onBrowserZoomShortcut:callback => { const listener=(_event,data) => callback(data); ipcRenderer.on('browser:zoom-shortcut',listener); return () => ipcRenderer.removeListener('browser:zoom-shortcut',listener); },
  onBrowserState:callback => { const listener=(_event,data) => callback(data); ipcRenderer.on('browser:state',listener); return () => ipcRenderer.removeListener('browser:state',listener); },
  pickDirectory:() => ipcRenderer.invoke('project:pick'),
  pickTerminalImages:() => ipcRenderer.invoke('terminal:images-pick'),
  pasteTerminalImage:() => ipcRenderer.invoke('terminal:image-paste'),
  createTerminal:(id,settings) => ipcRenderer.invoke('terminal:create',id,settings),
  writeTerminal:(id,data) => ipcRenderer.send('terminal:write',id,data),
  resizeTerminal:(id,cols,rows) => ipcRenderer.send('terminal:resize',id,cols,rows),
  closeTerminal:id => ipcRenderer.invoke('terminal:close',id),
  onTerminalData:callback => { const listener=(_event,data) => callback(data); ipcRenderer.on('terminal:data',listener); return () => ipcRenderer.removeListener('terminal:data',listener); },
  onTerminalExit:callback => { const listener=(_event,data) => callback(data); ipcRenderer.on('terminal:exit',listener); return () => ipcRenderer.removeListener('terminal:exit',listener); },
  onLaunchMode:callback => { const listener=(_event,mode) => callback(mode); ipcRenderer.on('desktop:mode',listener); return () => ipcRenderer.removeListener('desktop:mode',listener); },
}));
